"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CheckCircle2, ClipboardCheck, Gift, LogOut, Megaphone, Pencil, Plus, RefreshCw, Search, Store, Trash2, Trophy, Users } from "lucide-react";
import { Toaster, toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { DataRecord, EntityType } from "@/lib/types";

type Tab = EntityType | "redemptions";
const labels: Record<Tab, string> = { events: "活動", shops: "店家", challenges: "學習關卡", announcements: "公告", prizes: "獎品", members: "會員", redemptions: "兌獎核銷" };
const icons: Record<Tab, React.ReactNode> = { events: <CalendarDays />, shops: <Store />, challenges: <ClipboardCheck />, announcements: <Megaphone />, prizes: <Gift />, members: <Users />, redemptions: <CheckCircle2 /> };
const specs: Record<EntityType, { key: string; label: string; type?: string; required?: boolean }[]> = {
  events: [{key:"title",label:"活動名稱",required:true},{key:"summary",label:"活動摘要",type:"textarea",required:true},{key:"startAt",label:"開始日期",type:"date",required:true},{key:"endAt",label:"結束日期",type:"date",required:true},{key:"status",label:"狀態（draft / published）",required:true},{key:"rules",label:"活動規則",type:"textarea"}],
  shops: [{key:"name",label:"店家名稱",required:true},{key:"category",label:"分類",required:true},{key:"address",label:"地址",required:true},{key:"phone",label:"電話"},{key:"openHours",label:"營業時間"},{key:"bonusPoints",label:"加碼點數",type:"number"},{key:"description",label:"店家介紹",type:"textarea",required:true}],
  challenges: [{key:"title",label:"關卡名稱",required:true},{key:"category",label:"學習分類",required:true},{key:"description",label:"任務說明",type:"textarea",required:true},{key:"question",label:"題目",type:"textarea",required:true},{key:"answer",label:"標準答案",required:true},{key:"checkpointCode",label:"關卡碼",required:true},{key:"points",label:"獎勵點數",type:"number"},{key:"sortOrder",label:"排序",type:"number"}],
  announcements: [{key:"title",label:"公告標題",required:true},{key:"content",label:"公告內容",type:"textarea",required:true},{key:"level",label:"層級（info / warning）"},{key:"publishAt",label:"發布時間",type:"datetime-local",required:true}],
  prizes: [{key:"name",label:"獎品名稱",required:true},{key:"description",label:"獎品說明",type:"textarea",required:true},{key:"pointsCost",label:"兌換點數",type:"number",required:true},{key:"stock",label:"庫存",type:"number"},{key:"redemptionNote",label:"兌換須知",type:"textarea"}],
  members: [{key:"name",label:"會員姓名",required:true},{key:"phone",label:"手機",required:true},{key:"email",label:"Email"},{key:"points",label:"目前點數",type:"number"},{key:"status",label:"狀態（active / suspended）",required:true}],
};
const summaries: Record<EntityType,{primary:string;secondary:string;meta:string}> = { events:{primary:"title",secondary:"summary",meta:"status"}, shops:{primary:"name",secondary:"address",meta:"category"}, challenges:{primary:"title",secondary:"description",meta:"points"}, announcements:{primary:"title",secondary:"content",meta:"level"}, prizes:{primary:"name",secondary:"description",meta:"pointsCost"}, members:{primary:"name",secondary:"memberCode",meta:"points"} };

export function AdminDashboard() {
  const router = useRouter(); const [tab,setTab]=useState<Tab>("events"); const [records,setRecords]=useState<DataRecord[]>([]); const [demo,setDemo]=useState(false); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [editing,setEditing]=useState<DataRecord|null|"new">(null); const [deleting,setDeleting]=useState<DataRecord|null>(null); const [claim,setClaim]=useState("");
  async function load(target=tab) { setLoading(true); const url=target==="redemptions"?"/api/admin/redemptions":`/api/admin/content?type=${target}`; const response=await fetch(url,{cache:"no-store"}); if(response.status===401){router.replace("/admin/login");return;} const result=await response.json() as {records?:DataRecord[];demo?:boolean;error?:string}; setLoading(false); if(!response.ok){toast.error(result.error||"讀取失敗");return;} setRecords(result.records||[]); setDemo(Boolean(result.demo)); }
  // Synchronize the selected section with its API endpoint.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{void load(tab);},[tab]);
  const filtered=useMemo(()=>records.filter((row)=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[records,search]);
  async function save(form: FormData){ if(tab==="redemptions")return; const current=editing==="new"?null:editing; const body=Object.fromEntries(form.entries()) as Record<string,unknown>; body.isActive=form.get("isActive")==="on"; if(current)body.id=current.id; if(demo){ const next={...(current||{}),...body,id:current?.id||`demo-local-${Date.now()}`,isDemo:true,updatedAt:new Date().toISOString()} as DataRecord; setRecords((old)=>current?old.map((x)=>x.id===current.id?next:x):[next,...old]); setEditing(null); toast.success("示範變更只保留在目前瀏覽器畫面"); return; } const response=await fetch(`/api/admin/content?type=${tab}`,{method:current?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const result=await response.json() as {error?:string}; if(!response.ok){toast.error(result.error||"儲存失敗");return;} setEditing(null); await load(); toast.success("已儲存並同步至共用資料庫"); }
  async function remove(){if(!deleting||tab==="members"||tab==="redemptions")return;if(demo){setRecords((old)=>old.filter((x)=>x.id!==deleting.id));setDeleting(null);toast.success("已從目前示範畫面移除");return;}const response=await fetch(`/api/admin/content?type=${tab}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:deleting.id})});if(!response.ok){toast.error("刪除失敗");return;}setDeleting(null);await load();toast.success("已刪除");}
  async function verify(record?:DataRecord){const code=String(record?.claimCode||claim).trim().toUpperCase();if(!code){toast.error("請輸入核銷碼");return;}if(demo){setRecords((old)=>old.map((x)=>String(x.claimCode)===code?{...x,status:"verified",verifiedAt:new Date().toISOString()}:x));setClaim("");toast.success("示範核銷完成（未寫入正式資料庫）");return;}const response=await fetch("/api/admin/redemptions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({claimCode:code,status:"verified"})});const result=await response.json() as {error?:string};if(!response.ok){toast.error(result.error||"核銷失敗");return;}setClaim("");await load();toast.success("核銷完成");}
  const currentSpec=tab!=="redemptions"?specs[tab as EntityType]:[]; const current=editing==="new"?null:editing;
  return <main className="admin-shell"><Toaster position="top-center" richColors/><aside className="admin-sidebar"><div className="admin-brand"><span className="brand-mark">文</span><div><strong>文山真人大富翁</strong><small>營運管理台</small></div></div><nav>{(Object.keys(labels) as Tab[]).map((item)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{icons[item]}<span>{labels[item]}</span></button>)}</nav><button className="sidebar-logout" onClick={async()=>{await fetch("/api/session?role=admin",{method:"DELETE"});router.push("/admin/login");}}><LogOut/>登出</button></aside><section className="admin-main"><header className="admin-topbar"><div><p className="eyebrow">OPERATIONS</p><h1>{labels[tab]}管理</h1></div><a href="/" target="_blank">開啟手機前台 <ArrowUpRightIcon/></a></header>{demo&&<div className="admin-demo"><Trophy size={18}/><span><strong>示範資料模式</strong>：目前顯示的名稱、地址、會員、點數及兌換單都不是真實資料；畫面內編輯不會永久保存。</span></div>}<div className="admin-toolbar"><div className="search-box"><Search size={18}/><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder={`搜尋${labels[tab]}…`}/></div><Button variant="outline" size="icon" onClick={()=>load()} aria-label="重新整理"><RefreshCw/></Button>{tab!=="members"&&tab!=="redemptions"&&<Button onClick={()=>setEditing("new")}><Plus/>新增{labels[tab]}</Button>}</div>
  {tab==="redemptions"&&<div className="verify-bar"><div><ClipboardCheck/><span><strong>快速核銷</strong><small>輸入會員出示的核銷碼</small></span></div><Input value={claim} onChange={(e)=>setClaim(e.target.value)} placeholder="例如 WS-AB12CD34"/><Button onClick={()=>verify()}>確認核銷</Button></div>}
  <Tabs value={tab} onValueChange={(v)=>setTab(v as Tab)}><TabsList className="admin-mobile-tabs">{(Object.keys(labels) as Tab[]).map((item)=><TabsTrigger key={item} value={item}>{labels[item]}</TabsTrigger>)}</TabsList><TabsContent value={tab}><div className="admin-table-card">{loading?<div className="table-loading">資料載入中…</div>:<Table><TableHeader><TableRow><TableHead>{labels[tab]}內容</TableHead><TableHead>狀態／資訊</TableHead><TableHead>示範標記</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((record)=>tab==="redemptions"?<RedemptionRow key={record.id} record={record} onVerify={()=>verify(record)}/>:<EntityRow key={record.id} type={tab as EntityType} record={record} onEdit={()=>setEditing(record)} onDelete={()=>setDeleting(record)}/>)}</TableBody></Table>}</div></TabsContent></Tabs></section>
  <Dialog open={editing!==null} onOpenChange={(open)=>!open&&setEditing(null)}><DialogContent className="admin-edit-dialog"><DialogHeader><DialogTitle>{current?"編輯":"新增"}{labels[tab]}</DialogTitle><DialogDescription>儲存後，正式模式會同步更新共用資料庫與手機前台。</DialogDescription></DialogHeader><form action={save} className="admin-form">{currentSpec.map((field)=><label key={field.key}>{field.label}{field.type==="textarea"?<textarea name={field.key} defaultValue={String(current?.[field.key]||"")} required={field.required}/>:<input name={field.key} type={field.type||"text"} defaultValue={String(current?.[field.key]??"")} required={field.required}/>}</label>)}<label className="switch-row"><span>前台啟用</span><Switch name="isActive" defaultChecked={current?Boolean(current.isActive):true}/></label><DialogFooter><Button type="button" variant="outline" onClick={()=>setEditing(null)}>取消</Button><Button type="submit">儲存{labels[tab]}</Button></DialogFooter></form></DialogContent></Dialog>
  <AlertDialog open={Boolean(deleting)} onOpenChange={(open)=>!open&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>確定刪除「{String(deleting?.[summaries[tab as EntityType]?.primary]||"")}」？</AlertDialogTitle><AlertDialogDescription>這個動作無法復原；已有關聯資料時，資料庫可能會拒絕刪除。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={remove}>確認刪除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
function EntityRow({type,record,onEdit,onDelete}:{type:EntityType;record:DataRecord;onEdit:()=>void;onDelete:()=>void}){const view=summaries[type];return <TableRow><TableCell><strong className="row-title">{String(record[view.primary])}</strong><small className="row-subtitle">{String(record[view.secondary]||"")}</small></TableCell><TableCell><span className="table-badge">{String(record[view.meta]??"")}{["points","pointsCost"].includes(view.meta)?" 點":""}</span></TableCell><TableCell>{record.isDemo?<span className="demo-chip">示範</span>:"—"}</TableCell><TableCell><div className="row-actions"><Button size="icon-sm" variant="ghost" onClick={onEdit}><Pencil/></Button>{type!=="members"&&<Button size="icon-sm" variant="ghost" onClick={onDelete}><Trash2/></Button>}</div></TableCell></TableRow>}
function RedemptionRow({record,onVerify}:{record:DataRecord;onVerify:()=>void}){return <TableRow><TableCell><strong className="row-title">{String(record.prizeName)}</strong><small className="row-subtitle">{String(record.memberName)}・{String(record.claimCode)}</small></TableCell><TableCell><span className={`table-badge ${record.status}`}>{record.status==="pending"?"待核銷":record.status==="verified"?"已核銷":"已取消"}</span></TableCell><TableCell>{String(record.claimCode).includes("DEMO")?<span className="demo-chip">示範</span>:"—"}</TableCell><TableCell><div className="row-actions">{record.status==="pending"?<Button size="sm" onClick={onVerify}>核銷</Button>:<CheckCircle2 size={20}/>}</div></TableCell></TableRow>}
function ArrowUpRightIcon(){return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M7 17 17 7M7 7h10v10"/></svg>}
