import { integer, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

const audit = { isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), isDemo: integer("is_demo", { mode: "boolean" }).notNull().default(false), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };

export const events = sqliteTable("events", { id: text("id").primaryKey(), title: text("title").notNull(), summary: text("summary").notNull(), startAt: text("start_at").notNull(), endAt: text("end_at").notNull(), status: text("status").notNull().default("draft"), heroImage: text("hero_image"), rules: text("rules").notNull().default(""), ...audit }, (t) => [index("idx_events_status_dates").on(t.status, t.startAt, t.endAt)]);
export const shops = sqliteTable("shops", { id: text("id").primaryKey(), eventId: text("event_id").references(() => events.id), name: text("name").notNull(), category: text("category").notNull(), address: text("address").notNull(), phone: text("phone").notNull().default(""), description: text("description").notNull(), latitude: text("latitude"), longitude: text("longitude"), openHours: text("open_hours").notNull().default(""), bonusPoints: integer("bonus_points").notNull().default(0), ...audit }, (t) => [index("idx_shops_event_active").on(t.eventId, t.isActive)]);
export const challenges = sqliteTable("challenges", { id: text("id").primaryKey(), eventId: text("event_id").references(() => events.id), shopId: text("shop_id").references(() => shops.id), title: text("title").notNull(), category: text("category").notNull(), description: text("description").notNull(), question: text("question").notNull(), answer: text("answer").notNull(), checkpointCode: text("checkpoint_code").notNull(), points: integer("points").notNull().default(0), sortOrder: integer("sort_order").notNull().default(0), ...audit }, (t) => [uniqueIndex("idx_challenges_checkpoint_code").on(t.checkpointCode), index("idx_challenges_event_active_order").on(t.eventId, t.isActive, t.sortOrder)]);
export const announcements = sqliteTable("announcements", { id: text("id").primaryKey(), eventId: text("event_id").references(() => events.id), title: text("title").notNull(), content: text("content").notNull(), level: text("level").notNull().default("info"), publishAt: text("publish_at").notNull(), ...audit }, (t) => [index("idx_announcements_publish_active").on(t.isActive, t.publishAt)]);
export const prizes = sqliteTable("prizes", { id: text("id").primaryKey(), eventId: text("event_id").references(() => events.id), name: text("name").notNull(), description: text("description").notNull(), pointsCost: integer("points_cost").notNull(), stock: integer("stock").notNull().default(0), imageUrl: text("image_url"), redemptionNote: text("redemption_note").notNull().default(""), ...audit }, (t) => [index("idx_prizes_event_active").on(t.eventId, t.isActive)]);
export const members = sqliteTable("members", { id: text("id").primaryKey(), memberCode: text("member_code").notNull(), name: text("name").notNull(), phone: text("phone").notNull(), email: text("email").notNull().default(""), pinHash: text("pin_hash").notNull(), points: integer("points").notNull().default(0), status: text("status").notNull().default("active"), ...audit }, (t) => [uniqueIndex("idx_members_member_code").on(t.memberCode), uniqueIndex("idx_members_phone").on(t.phone), index("idx_members_status").on(t.status)]);
export const checkins = sqliteTable("checkins", { id: text("id").primaryKey(), memberId: text("member_id").notNull().references(() => members.id), challengeId: text("challenge_id").notNull().references(() => challenges.id), points: integer("points").notNull(), checkedInAt: text("checked_in_at").notNull() }, (t) => [uniqueIndex("idx_checkins_member_challenge").on(t.memberId, t.challengeId), index("idx_checkins_member_date").on(t.memberId, t.checkedInAt)]);
export const pointTransactions = sqliteTable("point_transactions", { id: text("id").primaryKey(), memberId: text("member_id").notNull().references(() => members.id), amount: integer("amount").notNull(), reason: text("reason").notNull(), referenceType: text("reference_type").notNull(), referenceId: text("reference_id").notNull(), createdAt: text("created_at").notNull() }, (t) => [index("idx_point_transactions_member_date").on(t.memberId, t.createdAt)]);
export const redemptions = sqliteTable("redemptions", { id: text("id").primaryKey(), memberId: text("member_id").notNull().references(() => members.id), prizeId: text("prize_id").notNull().references(() => prizes.id), pointsCost: integer("points_cost").notNull(), claimCode: text("claim_code").notNull(), status: text("status").notNull().default("pending"), requestedAt: text("requested_at").notNull(), verifiedAt: text("verified_at"), verifiedBy: text("verified_by"), note: text("note").notNull().default("") }, (t) => [uniqueIndex("idx_redemptions_claim_code").on(t.claimCode), index("idx_redemptions_status_date").on(t.status, t.requestedAt), index("idx_redemptions_member_date").on(t.memberId, t.requestedAt)]);
